// Copyright 2012 Google Inc. All rights reserved.
// Container Version: 3
(function(w,g){w[g]=w[g]||{};})(window,'google_tag_manager');(function(){








var Ja=this;/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var Ka=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,La=function(a){if(null==a)return String(a);var b=Ka.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},Ma=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},ra=function(a){if(!a||"object"!=La(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!Ma(a,"constructor")&&!Ma(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}for(var b in a);return void 0===
b||Ma(a,b)},Na=function(a,b){var c=b||("array"==La(a)?[]:{}),d;for(d in a)if(Ma(a,d)){var e=a[d];"array"==La(e)?("array"!=La(c[d])&&(c[d]=[]),c[d]=Na(e,c[d])):ra(e)?(ra(c[d])||(c[d]={}),c[d]=Na(e,c[d])):c[d]=e}return c};var wa=null,Oa=Math.random(),Pa=null,Qa=null,Da=!1,Ra={},Sa={},Ea={};var Ta,Va,Wa,Xa,Ya,Za,$a,ab,bb,cb,db,eb,S,fb,gb,hb,ib,jb,kb,lb,nb,pb,qb,rb,sb,tb,ub,vb,wb,xb,yb,zb,Ab,Bb,Cb,Db,Eb,Fb,Gb,Hb,Jb,Kb,Mb,Nb,Ob,Pb,Qb,Rb,Sb,Tb,Ub,Vb,Wb,Xb,Yb,Zb,$b,ac,bc,cc,dc,ec,fc,gc,hc,ic,jc,kc,lc,mc,nc,oc,pc,qc,sc,tc,uc,vc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Mc,Nc,Oc,U,Pc,Qc,Rc,Sc,Tc,Uc,Vc,Wc,Xc,Yc,Zc,$c,ad,bd,cd,dd,ed,fd,gd,hd,id,ld,od,pd,qd,rd,sd,td,ud,vd,wd,xd,yd,zd,Ad,Bd,Cd,Dd,Ed,Fd,Gd,Hd,Id,Jd,Kd,Ld,Md,Nd,Od,Pd,Qd,Rd,Sd,Td,Ud,Vd,Wd,Xd,Yd,Zd,$d,ae,be,ce,de,ee,fe,ge,he,
ie,je,ke,le,me,ne,oe,pe,qe,re,se,te,ue,ve,we,xe,ye,ze,Ae,Be,Ce,De,Ee,Fe,Ge,He,Ie,Je,Ke,Le,Me,Ne,Oe,Pe,Qe,Re,Se,Te,Ue,Ve,We,Xe;
(function(){var a=function(a){return{toString:function(){return a}}};Ta=a("");Va=a("");Wa="";Xa=a("");Ya=a("");Za=a("");$a=a("");ab=a("");bb=a("");cb=a("");db=a("");eb=a("0");S=a("1");fb=a("");gb=a("");hb=a("");
ib=a("");jb=a("");kb=a("");lb=a("");nb=a("");pb=a("");qb=a("");rb=a("");sb=a("");tb=a("");ub=a("");vb=a("");wb=a("");xb=a("");
yb=a("");zb=a("");Ab=a("");Bb=a("");Cb=a("");Db=a("");Eb=a("2");Fb=a("");Gb=a("");Hb=a("");Jb=a("");Kb=a("");Mb=a("");Nb=a("");Ob=a("");Pb=a("");Qb=a("");
Rb=a("");Sb=a("");Tb=a("");Ub=a("");Vb=a("3");Wb=a("4");Xb=a("");Yb=a("");Zb=a("");$b=a("");ac=a("");bc=a("");cc=a("");dc=a("");ec=a("");fc=a("");gc=a("");
hc=a("");ic=a("");jc=a("");kc=a("");lc=a("");mc=a("");nc=a("");oc=a("");pc=a("");qc=a("");sc=a("");tc=a("");uc=a("");vc=a("");wc=a("");xc=a("");
yc=a("");zc=a("");Ac=a("");Bc=a("");Cc=a("");Dc=a("");Ec=a("");Fc=a("");Gc=a("");Hc=a("");Ic=a("5");Jc=a("");Kc=a("12");Lc=a("13");Mc=a("");Nc=a("");Oc=a("6");
U=a("7");Pc=a("");Qc=a("");Rc=a("");Sc=a("");Tc=a("8");Uc=a("");Vc=a("");Wc=a("");Xc=a("");Yc=a("");Zc=a("");$c=a("");ad=a("");bd=a("");cd=a("");dd=a("");ed=a("");fd=a("");gd=
a("");hd=a("");id=a("");ld=a("");od=a("");pd=a("");qd=a("");rd=a("");sd=a("");td=a("");ud=a("");vd=a("");wd=a("");xd=a("");yd=a("");zd=a("");Ad=a("");Bd=a("");Cd=a("");Dd=a("");
Ed=a("");Fd=a("");Gd=a("");Hd=a("");Id=a("");Jd=a("");Kd=a("10");Ld=a("");Md=a("");Nd=a("");Od=a("");Pd=a("");Qd=a("");Rd=a("");Sd=a("");Td=a("");Ud=a("");Vd=a("");Wd=a("");
Xd=a("");Yd=a("");Zd=a("");$d=a("");ae=a("");be=a("");ce=a("");de=a("");ee=a("");fe=a("");ge=a("");he=a("");ie=a("");je=a("");ke=a("11");le=
a("");me=a("");ne=a("");oe=a("");pe=a("");qe=a("");re=a("");se=a("");te=a("");ue=a("");ve=a("");we=a("");xe=a("");ye=a("");ze=a("");Ae=a("");Be=a("");
Ce=a("");De=a("");Ee=a("");Fe=a("");Ge=a("");He="";Ie=a("");Je=a("");Ke=a("");Le=a("");Me=a("");Ne=a("");Oe=a("");Pe=a("");Qe=a("");Re=a("");Se=a("");Te=
a("");Ue=a("");Ve=a("");We=a("");Xe=a("")})();var Ye=function(){},M=function(a){return"function"==typeof a},Ze=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},$e=function(a){return"number"==La(a)&&!isNaN(a)},af=function(a){return/^[0-9]+$/.test(a)},bf=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},cf=function(a){return a?a.replace(/^\s+|\s+$/g,""):""},P=function(a){return Math.round(Number(a))||0},na=function(a){return"false"==
String(a).toLowerCase()?!1:!!a},df=function(a){var b=[];if(Ze(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));return b},E=function(){return new Date},ef=function(a,b){if(!$e(a)||!$e(b)||a>b)a=0,b=2147483647;return Math.round(Math.random()*(b-a)+a)},ff=function(){this.prefix="gtm.";this.values={}};ff.prototype.set=function(a,b){this.values[this.prefix+a]=b};ff.prototype.get=function(a){return this.values[this.prefix+a]};ff.prototype.contains=function(a){return void 0!==this.get(a)};
var gf=function(a,b,c){try{if(!a[id])return a[Ic](a,b||Ye,c||Ye);c&&c()}catch(d){}return!1},hf=function(a,b){function c(b,c){a.contains(b)||a.set(b,[]);a.get(b).push(c)}for(var d=cf(b).split("&"),e=0;e<d.length;e++)if(d[e]){var f=d[e].indexOf("=");0>f?c(d[e],"1"):c(d[e].substring(0,f),d[e].substring(f+1))}},jf=function(a){var b=a?a.length:0;return 0<b?a[b-1]:""},kf=function(a){return function(){return a("GTM-PT2SNS")}},lf=function(a){for(var b=0;b<a.length;b++)a[b]()},mf=E().getTime(),qa=function(){return"gtm"+
mf++},sa=function(a,b,c){return a&&a.hasOwnProperty(b)?a[b]:c},nf=function(a){return null!==a&&void 0!==a&&void 0!==a.length},of=function(a,b){0==b?a.Wa=!0:a.complete=!0;var c=a.g;a.s&&(a.s.Ha[c]=b);Ra[c]&&(Ra[c].state=b)},pf=function(a,b){a.sort(function(a,d){return b(a,d)?-1:b(d,a)?1:0})};var v=window,J=document,yf=navigator,O=function(a,b){var c=v[a];v[a]=void 0===c?b:c;return v[a]},I=function(a,b,c,d){return(d||"http:"!=v.location.protocol?a:b)+c},zf=function(a){var b=J.getElementsByTagName("script")[0]||J.body||J.head;b.parentNode.insertBefore(a,b)},ua=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},q=function(a,b,c){var d=J.createElement("script");d.type="text/javascript";d.async=
!0;d.src=a;ua(d,b);c&&(d.onerror=c);zf(d);return d},ga=function(a,b){var c=J.createElement("iframe");c.height="0";c.width="0";c.style.display="none";c.style.visibility="hidden";zf(c);ua(c,b);void 0!==a&&(c.src=a);return c},D=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a},R=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},y=function(a){v.setTimeout(a,0)},ya=!1,
za=[],Af=function(a){if(!ya){var b=J.createEventObject,c="complete"==J.readyState,d="interactive"==J.readyState;if(!a||"readystatechange"!=a.type||c||!b&&d){ya=!0;for(var e=0;e<za.length;e++)za[e]()}za.push=function(){for(var a=0;a<arguments.length;a++)y(arguments[a]);return 0}}},Bf=0,Cf=function(){if(!ya&&140>Bf){Bf++;try{J.documentElement.doScroll("left"),Af()}catch(a){v.setTimeout(Cf,50)}}},Ef=function(a){var b=J.getElementById(a);if(b&&Df(b,"id")!=a)for(var c=1;c<document.all[a].length;c++)if(Df(document.all[a][c],
"id")==a)return document.all[a][c];return b},Df=function(a,b){return a&&b&&a.attributes&&a.attributes[b]?a.attributes[b].value:null},Ha=function(a){return a.target||a.srcElement||{}},Ca=function(a){var b=J.createElement("div");b.innerHTML="A<div>"+a+"</div>";for(var b=b.lastChild,c=[];b.firstChild;)c.push(b.removeChild(b.firstChild));return c},Ff=function(a,b){for(var c={},d=0;d<b.length;d++)c[b[d]]=!0;for(var e=a,d=0;e&&!c[String(e.tagName).toLowerCase()]&&100>d;d++)e=e.parentElement;e&&!c[String(e.tagName).toLowerCase()]&&
(e=null);return e},Gf=!1,Hf=[],If=function(){if(!Gf){Gf=!0;for(var a=0;a<Hf.length;a++)Hf[a]()}},Jf=function(a){a=a||v;var b=a.location.href,c=b.indexOf("#");return 0>c?"":b.substring(c+1)},Aa=function(a){window.console&&window.console.log&&window.console.log(a)};var aa=function(a,b,c,d,e){var f,g=(a.protocol.replace(":","")||v.location.protocol.replace(":","")).toLowerCase();switch(b){case "protocol":f=g;break;case "host":f=(a.hostname||v.location.hostname).split(":")[0].toLowerCase();if(c){var h=/^www\d*\./.exec(f);h&&h[0]&&(f=f.substr(h[0].length))}break;case "port":f=String(1*(a.hostname?a.port:v.location.port)||("http"==g?80:"https"==g?443:""));break;case "path":f="/"==a.pathname.substr(0,1)?a.pathname:"/"+a.pathname;var k=f.split("/");0<=bf(d||[],k[k.length-
1])&&(k[k.length-1]="");f=k.join("/");break;case "query":f=a.search.replace("?","");if(e)a:{for(var l=f.split("&"),m=0;m<l.length;m++){var p=l[m].split("=");if(decodeURIComponent(p[0]).replace(/\+/g," ")==e){f=decodeURIComponent(p.slice(1).join("=")).replace(/\+/g," ");break a}}f=void 0}break;case "fragment":f=a.hash.replace("#","");break;default:f=a&&a.href}return f},Kf=function(a){var b="";a&&a.href&&(b=a.hash?a.href.replace(a.hash,""):a.href);return b},ba=function(a){var b=J.createElement("a");
a&&(b.href=a);return b};var ia=function(a,b){var c=function(){};c.prototype=a.prototype;var d=new c;a.apply(d,Array.prototype.slice.call(arguments,1));return d};var fa=function(a){var b=["veinteractive.com","ve-interactive.cn"];if(!a)return!1;var c=aa(ba(a),"host");if(!c)return!1;for(var d=0;b&&d<b.length;d++){var e=b[d]&&b[d].toLowerCase();if(e){var f=c.length-e.length;0<f&&"."!=e.charAt(0)&&(f--,e="."+e);if(0<=f&&c.indexOf(e,f)==f)return!0}}return!1},la=function(a,b,c){for(var d={},e=!1,f=0;a&&f<a.length;f++)a[f]&&a[f].hasOwnProperty(b)&&a[f].hasOwnProperty(c)&&(d[a[f][b]]=a[f][c],e=!0);return e?d:null};var Lf=new ff,Mf={},Of={set:function(a,b){Na(Nf(a,b),Mf)},get:function(a){return N(a,2)},reset:function(){Lf=new ff;Mf={}}},N=function(a,b){if(2==b){for(var c=Mf,d=a.split("."),e=0;e<d.length;e++){if(void 0===c[d[e]])return;c=c[d[e]]}return c}return Lf.get(a)},Nf=function(a,b){for(var c={},d=c,e=a.split("."),f=0;f<e.length-1;f++)d=d[e[f]]={};d[e[e.length-1]]=b;return c};var Pf=Math.random(),Qf="1.000000">Pf;var Rf=Ye;var Sf=Ye,Tf=[],Uf=!1,ca=function(a){return v["dataLayer"].push(a)},Vf=function(a){var b=!1;return function(){!b&&M(a)&&y(kf(a));b=!0}},ag=function(){for(var a=!1;!Uf&&0<Tf.length;){Uf=!0;var b=Tf.shift();if(M(b))try{b.call(Of)}catch(va){}else if(Ze(b))a:{var c=b;if("string"==La(c[0])){for(var d=c[0].split("."),e=d.pop(),f=c.slice(1),g=Mf,h=0;h<d.length;h++){if(void 0===g[d[h]])break a;g=g[d[h]]}try{g[e].apply(g,f)}catch(va){}}}else{var k=b,l=void 0;for(l in k)if(k.hasOwnProperty(l)){var m=l,
p=k[l];Lf.set(m,p);Na(Nf(m,p),Mf)}var r=!1,u=k.event,w=void 0;if(u){w=mf++;Qa=u;if(!k["gtm.uniqueEventId"]){var x=w;Lf.set("gtm.uniqueEventId",x);Na(Nf("gtm.uniqueEventId",x),Mf)}var A=Vf(k.eventCallback),F=k.eventTimeout;F&&v.setTimeout(A,Number(F));r=Sf(w,u,A,k.eventReporter)}Pa||(Pa=k["gtm.start"])&&Rf();var H=k,G=w,z=u,K=Mf;if(!r){var C=w,L=u;
}Qa=null;a=r||a}var T=b,Q=Mf;$f();Uf=!1}return!a},bg=function(){var a=ag();try{var b=v["dataLayer"].hide;if(b&&void 0!==b["GTM-PT2SNS"]&&b.end){b["GTM-PT2SNS"]=!1;var c=!0,d;for(d in b)if(!0===b[d]){c=!1;break}c&&(b.end(),
b.end=null)}}catch(e){}return a};var Ia=function(a,b){R(a,"load",b,void 0)},ea=function(a,b,c){q(a,b,c)},Fa=function(a,b){v[a]=b},n=function(a,b,c){var d=v;b&&(void 0===d[a]||c&&!d[a])&&(d[a]=b);return d[a]},t=function(a,b,c){return("https:"==v.location.protocol?a:b)+c};var cg=new RegExp(/^(.*\.)?(google|youtube|blogger|withgoogle)(\.com?)?(\.[a-z]{2})?\.?$/),dg={customPixels:["nonGooglePixels"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},eg={customPixels:["customScripts","html"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels",
"customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},fg=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c},gg=function(){var a=N("gtm.whitelist");
var b=a&&fg(df(a),dg),c=N("gtm.blacklist")||N("tagTypeBlacklist")||[];cg.test(v.location&&v.location.hostname)&&(c=df(c),c.push("nonGooglePixels","nonGoogleScripts"));var d=c&&fg(df(c),eg),e={};return function(f){var g=f&&f[Ic];if(!g)return!0;if(void 0!==e[g.a])return e[g.a];var h=!0;if(a)a:{if(0>bf(b,g.a))if(g.b&&0<g.b.length)for(var k=0;k<g.b.length;k++){if(0>bf(b,
g.b[k])){h=!1;break a}}else{h=!1;break a}h=!0}var l=!1;if(c){var m;if(!(m=0<=bf(d,g.a)))a:{for(var p=g.b||[],r=new ff,u=0;u<d.length;u++)r.set(d[u],!0);for(u=0;u<p.length;u++)if(r.get(p[u])){m=!0;break a}m=!1}l=m}return e[g.a]=!h||l}};var wf=function(a){var b=J;return hg?b.querySelectorAll(a):null},ig=!1;if(J.querySelectorAll)try{var jg=J.querySelectorAll(":root");jg&&1==jg.length&&jg[0]==J.documentElement&&(ig=!0)}catch(a){}var hg=ig;var _eu=function(a){var b=String(N("gtm.elementUrl")||a[ec]||""),c=ba(b);return b};_eu.a="eu";_eu.b=["google"];var _e=function(){return Qa};_e.a="e";_e.b=["google"];var og=/(^|\.)doubleclick\.net$/i,pg=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,oa=function(a){for(var b=String(J.cookie).split(";"),c=[],d=0;d<b.length;d++){var e=b[d].split("="),f=cf(e[0]);if(f&&f==a){var g=cf(e.slice(1).join("="));g&&(g=decodeURIComponent(g));c.push(g)}}return c},qg=function(a,b,c,d,e){if(og.test(J.location.hostname)||"/"==c&&pg.test(d))return!1;var f=a+"="+b+"; ";c&&(f+="path="+c+"; ");e&&(f+="expires="+e.toGMTString()+"; ");d&&(f+="domain="+d+";");var g=J.cookie;J.cookie=f;return g!=
J.cookie||0<=bf(oa(a),b)},rg=function(a){if("none"==a)return 0;0==a.indexOf(".")&&(a=a.substr(1));return a.split(".").length},sg=function(a){var b=a;b?(1<b.length&&b.lastIndexOf("/")==b.length-1&&(b=b.substr(0,b.length-1)),0!=b.indexOf("/")&&(b="/"+b),a=b):a="/";return"/"==a?1:a.split("/").length},tg=function(){var a=aa(v.location,"host",!0).split(".");if(4==a.length&&/^[0-9]*$/.exec(a[3]))return["none"];for(var b=[],c=a.length-2;0<=c;c--)b.push(a.slice(c).join("."));b.push("none");return b};var ug=function(a,b){this.f=a;this.j=b};ug.prototype.toString=function(){var a=""+this.f;1<this.j&&(a=a+"-"+this.j);return a};var vg=function(a,b){this.Fa=a;this.ja=b};vg.prototype.toString=function(){return""+this.ja+"."+this.Fa};var yg=function(a,b){var c=new wg(null,a,b);xg(c);return c},wg=function(a,b,c){this.Oa=Math.floor(E().getTime()/864E5);this.ia=b||"auto";this.Z=c||"/";var d=rg(this.ia),e=sg(this.Z);this.F=a||new ug(d,e);this.h=[];this.C=new ff},Ag=function(a,b,c){b&&(""==c.Fa?zg(a,b):(a.C.contains(b)||a.h.push(b),a.C.set(b,c)))},Bg=function(a,b){for(var c=0;c<b.length;c++)Ag(a,b[c][0],b[c][1])},zg=function(a,b){var c=bf(a.h,b);0<=c&&a.h.splice(c,1);a.C.set(b,void 0)},Cg=function(a){for(var b=[],c=0;c<a.h.length;c++){var d=
a.h[c];b.push([d,a.C.get(d)])}return b},Dg=function(a){for(var b=0,c=0;c<a.h.length;c++)b=Math.max(b,a.C.get(a.h[c]).ja);return 864E5*b};wg.prototype.toString=function(){if(0==this.h.length)return"";for(var a=[],b=0;b<this.h.length;b++){var c=this.h[b];a.push(""+c+"."+this.C.get(c).toString())}return"GAX1."+this.F.toString()+"."+a.join("!")};
var Eg=function(a,b){for(var c=new Date,d=sg(a.Z),e=[],f=0;f<a.h.length;f++){var g=a.h[f];a.C.get(g).ja<a.Oa&&e.push(g)}for(f=0;f<e.length;f++)zg(a,e[f]);if(a.h.length>(b||10))return!1;c.setTime(Dg(a));if("auto"!=a.ia)return qg("_gaexp",a.toString(),a.Z,a.ia,c);for(var h=tg(),k=0;k<h.length;k++)if("none"!=h[k]&&(a.F=new ug(rg(h[k]),d),qg("_gaexp",a.toString(),a.Z,h[k],c)))return!0;return!1},xg=function(a){for(var b=a.F.f,c=a.F.j,d=oa("_gaexp"),e=[],f=0;f<d.length;f++){var g=Fg(a,d[f]);g&&e.push(g)}pf(e,
function(a,d){var e=a.F,f=d.F;return e.f==f.f&&e.j==f.j?!1:e.f==b&&e.j==c?!0:f.f==b&&f.j==c?!1:e.f==b?f.f!=b||e.j<f.j:f.f==b?!1:e.j==c?f.f!=b&&(f.j!=c||e.f<f.f):f.j==c?!1:e.f<f.f||e.f==f.f&&e.j<f.j});a.F=0<e.length?e[0].F:new ug(b,c);for(f=e.length-1;0<=f;f--)Bg(a,Cg(e[f]))},Fg=function(a,b){var c=b.match(/GAX1\.([^.]+).(.*)/);if(c){var d;a:{var e=(c[1]||"").split("-");if(!(0==e.length||2<e.length)){var f=cf(e[0]);if(0!=f.length){var g=2==e.length?cf(e[1]):"1";if(af(f)&&af(g)){d=new ug(P(f),P(g));
break a}}}d=void 0}if(d){for(var h=new wg(d,a.ia,a.Z),k=(c[2]||"").split("!"),l=0;l<k.length;l++){var m=k[l].split(".");if(3==m.length){if(!af(m[1]))return;Ag(h,m[0],new vg(m[2],P(m[1])))}}return h}}};var _f=function(a){var b=String(N("gtm.referrer")||J.referrer);if(!b)return b;var c=ba(b);return b};_f.a="f";_f.b=["google"];var ja=function(a){var b=v.location,c;(c=a[Ub]?a[Ub]:N("gtm.url"))&&(b=ba(String(c)));var d=b.href,e=d.indexOf("#"),f=0>e?d:d.substr(0,e);a[Eb]&&(f=aa(b,a[Eb],a[ee],a[dc],a[Sd]));return f},_u=ja;_u.a="u";_u.b=["google"];var _eq=function(a){return String(a[eb])==String(a[S])};_eq.a="eq";_eq.b=["google"];
var _asp=function(a,b,c){v.adroll_adv_id=a[Wb];v.adroll_pix_id=a[Kd];
v.__adroll_loaded=!0;q(I("https://s","http://a",".adroll.com/j/roundtrip.js"),b,c)};_asp.a="asp";_asp.b=["nonGoogleScripts"];var Gg=new String("undefined"),Tg=function(a){this.resolve=function(b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]===Gg?b:a[d]);return c.join("")}};Tg.prototype.toString=function(){return this.resolve("undefined")};Tg.prototype.valueOf=Tg.prototype.toString;var Ug={},Vg=function(a,b){var c=mf++;Ug[c]=[a,b];return c},Wg=function(a){var b=a?0:1;return function(a){var c=Ug[a];if(c&&M(c[b]))c[b]();Ug[a]=void 0}};var Xg=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},Yg=function(a,b){return a<b?-1:a>b?1:0};var Zg;a:{var $g=Ja.navigator;if($g){var ah=$g.userAgent;if(ah){Zg=ah;break a}}Zg=""}var W=function(a){return-1!=Zg.indexOf(a)};var bh=function(a){bh[" "](a);return a};bh[" "]=function(){};var dh=function(a,b){var c=ch;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var eh=W("Opera"),fh=W("Trident")||W("MSIE"),gh=W("Edge"),hh;if(hh=W("Gecko"))hh=!(-1!=Zg.toLowerCase().indexOf("webkit")&&!W("Edge"));var ih=hh&&!(W("Trident")||W("MSIE"))&&!W("Edge"),jh=-1!=Zg.toLowerCase().indexOf("webkit")&&!W("Edge");jh&&W("Mobile");W("Macintosh");W("Windows");W("Linux")||W("CrOS");var kh=Ja.navigator||null;kh&&(kh.appVersion||"").indexOf("X11");W("Android");!W("iPhone")||W("iPod")||W("iPad");W("iPad");W("iPod");
var lh=function(){var a=Ja.document;return a?a.documentMode:void 0},mh;a:{var nh="",oh=function(){var a=Zg;if(ih)return/rv\:([^\);]+)(\)|;)/.exec(a);if(gh)return/Edge\/([\d\.]+)/.exec(a);if(fh)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(jh)return/WebKit\/(\S+)/.exec(a);if(eh)return/(?:Version)[ \/]?(\S+)/.exec(a)}();oh&&(nh=oh?oh[1]:"");if(fh){var ph=lh();if(null!=ph&&ph>parseFloat(nh)){mh=String(ph);break a}}mh=nh}
var qh=mh,ch={},rh=function(a){return dh(a,function(){for(var b=0,c=Xg(String(qh)).split("."),d=Xg(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"";do{var k=/(\d*)(\D*)(.*)/.exec(g)||["","","",""],l=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==k[0].length&&0==l[0].length)break;b=Yg(0==k[1].length?0:parseInt(k[1],10),0==l[1].length?0:parseInt(l[1],10))||Yg(0==k[2].length,0==l[2].length)||Yg(k[2],l[2]);g=k[3];h=l[3]}while(0==b)}return 0<=b})},sh;
var th=Ja.document;sh=th&&fh?lh()||("CSS1Compat"==th.compatMode?parseInt(qh,10):5):void 0;var uh;if(!(uh=!ih&&!fh)){var vh;if(vh=fh)vh=9<=Number(sh);uh=vh}uh||ih&&rh("1.9.1");fh&&rh("9");var Ba=function(a,b){var c="";fh&&!wh(a)&&(c='<script>document.domain="'+document.domain+'";\x3c/script>'+c);var d="<!DOCTYPE html><html><head><script>var inDapIF=true;\x3c/script>"+c+"</head><body>"+b+"</body></html>";if(xh)a.srcdoc=d;else if(yh){var e=a.contentWindow.document;e.open("text/html","replace");e.write(d);e.close()}else zh(a,d)},xh=jh&&"srcdoc"in document.createElement("iframe"),yh=ih||jh||fh&&rh(11),zh=function(a,b){fh&&rh(7)&&!rh(10)&&6>Ah()&&Bh(b)&&(b=Ch(b));var c=function(){a.contentWindow.goog_content=
b;a.contentWindow.location.replace("javascript:window.goog_content")};fh&&!wh(a)?Dh(a,c):c()},Ah=function(){var a=navigator.userAgent.match(/Trident\/([0-9]+.[0-9]+)/);return a?parseFloat(a[1]):0},wh=function(a){try{var b;var c=a.contentWindow;try{var d;if(d=!!c&&null!=c.location.href)b:{try{bh(c.foo);d=!0;break b}catch(e){}d=!1}b=d}catch(e){b=!1}return b}catch(e){return!1}},Eh=0,Dh=function(a,b){var c="goog_rendering_callback"+Eh++;window[c]=b;a.src="javascript:'<script>(function() {document.domain = \""+
document.domain+'";var continuation = window.parent.'+c+";window.parent."+c+" = null;continuation();})()\x3c/script>'"},Bh=function(a){for(var b=0;b<a.length;++b)if(127<a.charCodeAt(b))return!0;return!1},Ch=function(a){for(var b=unescape(encodeURIComponent(a)),c=Math.floor(b.length/2),d=[],e=0;e<c;++e)d[e]=String.fromCharCode(256*b.charCodeAt(2*e+1)+b.charCodeAt(2*e));1==b.length%2&&(d[c]=b.charAt(b.length-1));return d.join("")};/*
 Copyright (c) 2014 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */

var Gh=function(a,b,c,d){return function(){try{if(0<b.length){var e=b.shift(),f=Gh(a,b,c,d);if("SCRIPT"==String(e.nodeName).toUpperCase()&&"text/gtmscript"==e.type){var g=J.createElement("script");g.async=!1;g.type="text/javascript";g.id=e.id;g.text=e.text||e.textContent||e.innerHTML||"";e.charset&&(g.charset=e.charset);var h=e.getAttribute("data-gtmsrc");h&&(g.src=h,ua(g,f));a.insertBefore(g,null);h||f()}else if(e.innerHTML&&0<=e.innerHTML.toLowerCase().indexOf("<script")){for(var k=[];e.firstChild;)k.push(e.removeChild(e.firstChild));
a.insertBefore(e,null);Gh(e,k,f,d)()}else a.insertBefore(e,null),f()}else c()}catch(l){y(d)}}};var Ih=function(a,b,c){if(J.body){var d=
a[Oc];d instanceof Tg&&(d=d.resolve(Vg(b,c)),b=Ye);if(a[Oe])try{Ba(ga(),"<script>var google_tag_manager=parent.google_tag_manager;\x3c/script>"+d),y(b)}catch(e){y(c)}else a[Qe]?Hh(d,b,c):Gh(J.body,Ca(d),b,c)()}else v.setTimeout(function(){Ih(a,b,c)},200)},_html=Ih;_html.a="html";_html.b=["customScripts"];
var Uh=function(a,b,c,d){var e=b+": "+c+(d?" !important":""),f=document;if(f.createStyleSheet){var g=Rh(f),h=g.rules.length;g.addRule(a,e);return function(){g.removeRule?g.removeRule(h):g.deleteRule(h);g.addRule("x","-",h)}}var k=Sh(a+"{"+e+"}",f);Th(k,f);var l=k.parentNode;return function(){l.removeChild(k)}},Vh=null,Rh=function(a){if(Vh)return Vh;for(var b=a.styleSheets.length-1;0<=b;b--){var c=a.styleSheets[b],d=c.ownerNode;if(d&&d.parentNode&&"HEAD"==d.parentNode.tagName)return Vh=c}0==a.styleSheets.length&&
a.createStyleSheet();return Vh=a.styleSheets[0]},Sh=function(a,b){var c=(b||document).createElement("style");void 0!==c.cssText?c.cssText=a:c.innerHTML=a;return c},Th=function(a,b){var c=b||document,d=c.getElementsByTagName("head")[0];d||(d=c.createElement("head"),c.body.parentNode.insertBefore(d,c.body));d.appendChild(a)};var bi={},ci=void 0,di=function(a){var b=bi[a];b||(b={id:a,v:[],W:0,Ia:null,za:void 0,Da:!1},bi[a]=b);ci=b},fi=function(a,b,c,d){var e=ci;if(!hg||!e)return!1;var f={id:e.id+":"+e.v.length,eb:b,U:[],Za:c,G:a,ta:0,ra:d||null,Na:0,V:!1};e.v.push(f);null===a?(f.V=!0,b(null)):ei(e);return!0},gi=function(a){var b=Uh(a,"visibility","hidden",!0);return function(){M(b)&&b.apply();b=null}},hi=function(a,b,c,d){var e=b;if(!ya){var f=gi(a.A);za.push(f);e=function(a,c){var d=b(a,c);f();return d}}return fi(a,e,
c,d)},ei=function(a){if(!a.Da){for(var b=a.W;b<a.v.length;b++){var c=a.v[b],d=b==a.W;if(!c.V&&!ii(d,c))break;c.V&&d&&a.W++}a.v.length>a.W?(a.Ia||(a.Ia=v.setTimeout(function(){a.Ia=null;ei(a)},80)),ya||a.za||(a.za=function(){y(function(){ei(a)})},R(J,"DOMContentLoaded",a.za))):ji(a)}},ji=function(a){for(var b=0;b<a.v.length;b++){var c=a.v[b];if(c.G)for(var d=wf(c.G.A)||[],e=0;e<d.length;e++){var f=d[e];f.gtmProgressiveApplied&&f.gtmProgressiveApplied[c.id]||(ki(f,c.id),c.U.push(li(f,c.id)))}}},ii=
function(a,b){var c=[];if(b.G){var d=mi(b.G,b.id),e=null;b.ra&&(e=mi(b.ra,b.id+"-t"));for(var f=0;f<d.length;f++){var g=d[f],h;if(null!=e&&(h=e.length>f?e[f]:null,!h&&!ya&&(null===b.ra.o||b.Na+c.length<b.ra.o)))break;c.push({element:g,Hb:h})}}if(!ya&&b.Za&&(!a||null==b.G.o||b.G.o!=b.ta+c.length))return!1;for(var k=0;k<c.length;k++){var l=c[k].element,m=c[k].Hb,p;b.ta++;ki(l,b.id);m&&(b.Na++,p=b.id+"-t",ki(m,p));var r=b.eb(l,m);M(r)&&b.U.push(r);b.U.push(li(l,b.id));m&&p&&b.U.push(li(m,p))}if(b.G.o&&
b.G.o==b.ta||ya)b.V=!0;return!0},ki=function(a,b){a.gtmProgressiveApplied||(a.gtmProgressiveApplied={});a.gtmProgressiveApplied[b]=!0},li=function(a,b){return function(){a.gtmProgressiveApplied&&delete a.gtmProgressiveApplied[b]}},mi=function(a,b){for(var c=wf(a.A)||[],d=[],e=0;e<c.length;e++){var f=c[e];if(!f.gtmProgressiveApplied||!f.gtmProgressiveApplied[b]){if(a.D&&!ni(f))break;d.push(f)}}return d},ni=function(a){if(ya)return!0;for(;a;){if(a.nextSibling)return!0;a=a.parentNode}return!1};var oi,pi,qi,ri=/(Firefox\D28\D)/g.test(yf.userAgent),xi=function(a,b){return function(c){c=c||v.event;var d=Ha(c),e=!1;if(3!==c.which||"LINK_CLICK"!=a){"LINK_CLICK"==a&&(d=Ff(d,["a","area"]),e=!d||!d.href||si(d.href)||2===c.which||null==c.which&&4==c.button||c.ctrlKey||c.shiftKey||c.altKey||!0===c.metaKey);var f="FORM_SUBMIT"==a?qi:pi;if(c.defaultPrevented||!1===c.returnValue||c.wa&&c.wa()){if(d){var g={simulateDefault:!1},h=ti(f,["wnc","nwnc"]);h&&ui(a,d,g,f.wt,h)}}else{if(d){var g={},k,l=ti(f,
["wnc","nwnc","nwc","wc"]);(k=ui(a,d,g,f.wt,l))||(vi(g.eventReport,f)?b=!0:e=!0);e=e||k||"LINK_CLICK"==a&&ri;g.simulateDefault=!k&&b&&!e;g.simulateDefault&&(e=wi(d,g)||e,!e&&c.preventDefault&&c.preventDefault());c.returnValue=k||!b||e;return c.returnValue}return!0}}}},ui=function(a,b,c,d,e){var f=d||2E3,g={"gtm.element":b,"gtm.elementClasses":b.className,"gtm.elementId":b["for"]||Df(b,"id")||"","gtm.elementTarget":b.formTarget||b.target||""};switch(a){case "LINK_CLICK":g["gtm.triggers"]=e||"";g.event=
"gtm.linkClick";g["gtm.elementUrl"]=b.href;g.eventTimeout=f;g.eventCallback=yi(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "FORM_SUBMIT":g["gtm.triggers"]=e||"";g.event="gtm.formSubmit";g["gtm.elementUrl"]=zi(b);g.eventTimeout=f;g.eventCallback=Ai(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "CLICK":g.event="gtm.click";g["gtm.elementUrl"]=(b.attributes&&b.attributes.formaction?b.formAction:"")||b.action||b.href||b.src||b.code||b.codebase||"";break;default:return!0}return ca(g)},
zi=function(a){var b=a.action;b&&b.tagName&&(b=a.cloneNode(!1).action);return b},Bi=function(a){var b=a.target;if(!b)switch(String(a.tagName).toLowerCase()){case "a":case "area":case "form":b="_self"}return b},wi=function(a,b){var c=!1,d=/(iPad|iPhone|iPod)/g.test(yf.userAgent),e=Bi(a).toLowerCase();switch(e){case "":case "_self":case "_parent":case "_top":var f;f=(e||"_self").substring(1);b.targetWindow=v.frames&&v.frames[f]||v[f];break;case "_blank":d?(b.simulateDefault=!1,c=!0):(b.targetWindowName=
"gtm_autoEvent_"+E().getTime(),b.targetWindow=v.open("",b.targetWindowName));break;default:d&&!v.frames[e]?(b.simulateDefault=!1,c=!0):(v.frames[e]||(b.targetWindowName=e),b.targetWindow=v.frames[e]||v.open("",e))}return c},yi=function(a,b,c){return function(){b.simulateDefault&&(b.targetWindow?b.targetWindow.location.href=a.href:(c=c||E().getTime(),500>E().getTime()-c&&v.setTimeout(yi(a,b,c),25)))}},Ai=function(a,b,c){return function(){if(b.simulateDefault)if(b.targetWindow){var d;b.targetWindowName&&
(d=a.target,a.target=b.targetWindowName);J.gtmSubmitFormNow=!0;Ci(a).call(a);b.targetWindowName&&(a.target=d)}else c=c||E().getTime(),500>E().getTime()-c&&v.setTimeout(Ai(a,b,c),25)}},ti=function(a,b){for(var c=[],d=0;d<b.length;d++){var e=a[b[d]],f;for(f in e)e.hasOwnProperty(f)&&e[f]&&c.push(f)}return c.join(",")},Di=function(a,b,c,d,e){var f=e;if(!f||"0"==f){if(a.l)return;a.l=!0;f="0"}var g=a.wt;b&&(!g||g>d)&&(a.wt=d);a[b?c?"wc":"wnc":c?"nwc":"nwnc"][f]=!0},vi=function(a,b){if(b.wnc["0"]||b.wc["0"])return!0;
for(var c=0;c<Ei.length;c++)if(a.passingRules[c]){var d=Fi[c],e=d&&d[0]&&d[0][0]||d[1]&&d[1][0];if(e&&"0"!=e&&(b.wc[e]||b.wnc[e]))for(var f=Ei[c][1],g=0;g<f.length;g++)if(a.resolvedTags[f[g]])return!0}return!1},pa=function(a,b,c,d,e){var f,g,h=!1;switch(a){case "CLICK":if(J.gtmHasClickListenerTag)return;J.gtmHasClickListenerTag=!0;f="click";g=function(a){var b=Ha(a);b&&ui("CLICK",b,{},d)};h=!0;break;case "LINK_CLICK":b&&!oi&&(oi=Kf(J.location));Di(pi,b||!1,c||!1,d,e);if(J.gtmHasLinkClickListenerTag)return;
J.gtmHasLinkClickListenerTag=!0;f="click";g=xi(a,b||!1);break;case "FORM_SUBMIT":Di(qi,b||!1,c||!1,d,e);if(J.gtmHasFormSubmitListenerTag)return;J.gtmHasFormSubmitListenerTag=!0;f="submit";g=xi(a,b||!1);break;default:return}R(J,f,g,h)},si=function(a){if(!oi)return!0;var b=a.indexOf("#");if(0>b)return!1;if(0==b)return!0;var c=ba(a);return oi==Kf(c)},Ci=function(a){try{if(a.constructor&&a.constructor.prototype)return a.constructor.prototype.submit}catch(b){}if(a.gtmReplacedFormSubmit)return a.gtmReplacedFormSubmit;
J.gtmFormElementSubmitter||(J.gtmFormElementSubmitter=J.createElement("form"));return J.gtmFormElementSubmitter.submit.call?J.gtmFormElementSubmitter.submit:a.submit};var ta=function(a,b){var c=b||Ja,d=c.onerror,e=!1;jh&&!rh("535.3")&&(e=!e);c.onerror=function(b,c,h,k,l){d&&d(b,c,h,k,l);a({message:b,fileName:c,Sa:h,Xb:k,error:l});return e}};var Dj=28,Ej=[],Fj=[],Gj=[],Hj=new ff,Ij=[],Z=[],Ei=[],Fi=[],Jj=function(){this.L=[]};Jj.prototype.set=function(a,b){this.L.push([a,b]);return this};Jj.prototype.resolve=function(a,b){for(var c={},d=0;d<this.L.length;d++){var e=Kj(this.L[d][0],a,b),f=Kj(this.L[d][1],a,b);c[e]=f}return c};var Lj=function(a){this.index=a};Lj.prototype.resolve=function(a,b){var c=Gj[this.index];if(c&&!b(c)){var d=c[Tc];if(a){if(a.get(d))return;a.set(d,!0)}c=Kj(c,a,b);a&&a.set(d,!1);return gf(c)}};
var _M=function(a){return new Lj(a)},Mj=function(a){this.resolve=function(b,c){for(var d=[],e=!1,f=0;f<a.length;f++){var g=Kj(Ej[a[f]],b,c);g===Gg&&(e=!0);d.push(g)}return e?new Tg(d):d.join("")}},_T=function(a){return new Mj(arguments)},Nj=function(a){function b(b){for(var c=1;c<a.length;c++)if(a[c]==b)return!0;return!1}this.resolve=
function(c,d){var e=Kj(a[0],c,d);if(a[0]instanceof Lj&&b(8)&&b(16)){if(e===Gg)return e;var f=qa();Hj.set(f,e);return'google_tag_manager["GTM-PT2SNS"].macro(\''+f+"')"}for(var e=String(e),g=1;g<a.length;g++)e=Y[a[g]](e);return e}},_E=function(a,b){return new Nj(arguments)},Oj=function(a,b){this.w=a;this.qa=b},_R=function(a,b){return new Oj(a,b)},Kj=function(a,b,c){var d=a;if(a instanceof Lj||a instanceof Jj||a instanceof Mj||a instanceof Nj)return a.resolve(b,c);if(!(a instanceof Oj))if(Ze(a))for(var d=
[],e=0;e<a.length;e++)d[e]=Kj(a[e],b,c);else if(a&&"object"==typeof a){var d={},f;for(f in a)a.hasOwnProperty(f)&&(d[f]=Kj(a[f],b,c))}return d},Pj=function(a,b){var c=b[a],d=c;if(c instanceof Lj||c instanceof Nj||c instanceof Mj||c instanceof Oj)d=c;else if(Ze(c))for(var d=[],e=0;e<c.length;e++)d[e]=Pj(c[e],b);else if("object"==typeof c){var d=new Jj,f;for(f in c)c.hasOwnProperty(f)&&d.set(b[f],Pj(c[f],b))}return d},Rj=function(a,b){for(var c=b?b.split(","):[],d=0;d<c.length;d++){var e=c[d]=c[d].split(":");
0==a&&(e[1]=Ej[e[1]]);if(1==a)for(var f=Qj(e[0]),e=c[d]={},g=0;g<f.length;g++){var h=Fj[f[g]];e[h[0]]=h[1]}if(2==a)for(g=0;4>g;g++)e[g]=Qj(e[g]);3==a&&(c[d]=Ej[e[0]]);if(4==a)for(g=0;2>g;g++)if(e[g]){e[g]=e[g].split(".");for(var k=0;k<e[g].length;k++)e[g][k]=Ej[e[g][k]]}else e[g]=[];5==a&&(c[d]=e[0])}return c},Qj=function(a){var b=[];if(!a)return b;for(var c=0,d=0;d<a.length&&c<Dj;c+=6,d++){var e=a&&a.charCodeAt(d)||65;if(65!=e){var f;f=65<e&&90>=e?e-65:97<=e&&122>=e?e-97+26:95==e?63:48<=e?e-48+52:
62;1&f&&b.push(c);2&f&&b.push(c+1);4&f&&b.push(c+2);8&f&&b.push(c+3);16&f&&b.push(c+4);32&f&&b.push(c+5)}}return b},Sj=function(a,b,c){a.push.apply(a,Rj(b,c))};
var Xf=function(){},ak=function(a){},$f=function(){},bk=function(a){},ck=function(a,b){},dk=function(a,b){},Yf=function(a){};var ek,fk;var pk=function(a){return function(){}},qk=function(a){return function(){}};var rk=function(a){var b=this;this.g=a;this.complete=this.Wa=!1;this.pa=[];this.ka=[];this.S=function(){if(b.s&&b.s.event){var c=b.s.event,d=b.g;}b.complete||lf(b.pa);of(b,1);if(Sa[a])for(var e=0;e<Sa[a].length;e++)Sa[a].shift().S()};this.R=function(){if(b.s&&b.s.event){var c=b.s.event,d=b.g;}b.complete||
lf(b.ka);of(b,2);if(Sa[a])for(var e=0;e<Sa[a].length;e++)Sa[a].shift().R()};this.B=Ye},sk=function(a,b){a.pa.push(b)},tk=function(a,b){a.ka.push(b)},uk=function(a){this.M=[];this.Ga=[];this.Pa={};this.ya=[];this.X=0;this.Va={};this.Xa={};this.Ha={};this.event=a};uk.prototype.addListener=function(a){this.ya.push(a)};
var vk=function(a,b,c,d,e,f){if(!c.complete){a.M[b]=c;void 0==d&&(d=[]);void 0==e&&(e=[]);void 0==f&&(f=[]);d=Ze(d)?d.slice():["or",d];e=Ze(e)?e.slice():[e];f=Ze(f)?f.slice():[f];a.Pa[b]=d;a.Va[b]=0<e.length;a.Xa[b]=0<f.length;a.X++;var g=function(){0<a.X&&a.X--;0<a.X||lf(a.ya)};sk(c,g);tk(c,g)}},wk=function(a,b,c){a.M[b]&&(sk(a.M[b],function(){c(b,!0)}),tk(a.M[b],function(){c(b,!1)}))},xk=function(a,b){var c=!1;return function(d,e){var f;a:{for(var g=0;g<a.length;g++)if(a[g]instanceof Oj&&a[g].w===
d||a[g]===d){f=g;break a}f=-1}c||0>f||("or"==a[0]?e?(c=!0,b()):(a.splice(f,1),1==a.length&&(c=!0)):e?(a.splice(f,1),1==a.length&&(c=!0,b())):c=!0)}},Bk=function(a,b){var c=[],d=!1,e=function(b){var f,g,h=Z[b];if(a.event.c(h)){}else g=yk(h,b,a);if(f=g){var k=zk(b,!0);0<k.length&&e(k[0].w);c.push(f);var l=zk(b,!1);0<l.length&&e(l[0].w)}else d=
!0};e(b);if(!d){for(var f=0;f<c.length;f++){var g=c[f],h=zk(g.g,!0);if(0<h.length){var k=c[f-1],l=Ak(g);sk(k,l);0==h[0].qa&&tk(k,l)}var m=zk(g.g,!1);0<m.length&&(l=Ak(c[f+1]),sk(g,l),0==m[0].qa&&tk(g,l))}a.Ga.push(c)}},zk=function(a,b){var c=b?be:se,d=Z[a],e=void 0===d[c]?[]:d[c];return Ze(e)?e:[e]},Ak=function(a){return function(){a.B()}},Dk=function(a){for(var b={},c=0;c<a.length;c++){var d=a[c],e=[],f=function(a){var b=zk(a,!0);0<b.length&&f(b[0].w);e.push(a);var c=zk(a,!1);0<c.length&&f(c[0].w)};
f(d.g);b[d.g]=e}Ck(a,b);return b},Ck=function(a,b){for(var c=0;c<a.length;c++){var d=a[c].g,e;for(e in b)if(b.hasOwnProperty(e)&&e!=d&&-1<bf(b[e],d)){delete b[d];break}}};var Fk=function(a,b){return function(){a[Kc]=b.S;a[Lc]=b.R;var c=b.g,d=b.s&&b.s.Ha[c],e=Ra[c]&&Ra[c].state,f=d?void 0!==d:b.Wa||b.Yb,g=Ra[c]&&Ra[c].firingOption,h=g&&2==g,k=g&&1==g;if(!f&&void 0===e||!f&&!h||!h&&!k){of(b,0);var l=b.s?b.s.event:void 0;a=Ek(a,l?l.c:gg());if(l){var m=a;ck(l,c)}gf(a,b.S,b.R)}else h&&0==e||k&&0==d?Sa[c].push(b):h&&1==e||k&&1==d?b.S():b.R()}},Ek=function(a,b){a=Kj(a,new ff,b);return a},yk=function(a,b,c){var d=new rk(b);d.s=c;sk(d,pk(a));tk(d,qk(a));d.B=Fk(a,d);return d};var _sp=function(a,b,c){q("//www.googleadservices.com/pagead/conversion_async.js",function(){var d=v.google_trackConversion;M(d)?d({google_conversion_id:a[U],google_conversion_label:a[Zc],google_custom_params:a[Vb]||{},google_remarketing_only:!0,onload_callback:b})||c():c()},c)};_sp.a="sp";_sp.b=["google"];var Kk=!1;var Lk=function(){var a=[];return function(b,c){if(void 0===a[b]){var d=Ij[b]&&Kj(Ij[b],new ff,c),e=d;if(d)if(d[db]&&Ze(d[S]))for(var f=d[S],e=!1,g=0;!e&&g<f.length;g++)d[S]=f[g],e=gf(d);else e=gf(d);a[b]=[e,d]}return a[b]}},Zj=function(a,b){for(var c=b[0],d=0;d<c.length;d++)if(!a.P(c[d],a.c)[0])return!1;for(var e=b[2],d=0;d<e.length;d++)if(a.P(e[d],a.c)[0])return!1;return!0},Mk=!1,Sf=function(a,b,c,d){switch(b){case "gtm.js":if(Mk)return!1;Mk=!0;break;case "gtm.sync":if(N("gtm.snippet")!=Oa)return!1}N("tagTypeBlacklist");
for(var e={id:a,name:b,fa:c||Ye,ea:Qj(),oa:Qj(),P:Lk(),c:gg()},f=[],g=0;g<Ei.length;g++)if(Zj(e,Ei[g])){f[g]=!0;for(var h=e,k=Ei[g],l=k[1],m=0;m<l.length;m++)h.ea[l[m]]=!0;for(var p=k[3],m=0;m<p.length;m++)h.oa[p[m]]=!0}else f[g]=!1;ck(e);var u=[];for(var w=0;w<Dj;w++)if(e.ea[w]&&!e.oa[w])if(e.c(Z[w])){}else{u[w]=Z[w];}e.T=u;for(var x=new uk(e),A=0;A<Dj;A++)if(e.ea[A]&&!e.oa[A])if(e.c(Z[A])){}else{var F=e.T[A],H=yk(F,A,x);vk(x,A,H,F[fc],F[be],F[se]);if(F[Ta])break}x.addListener(e.fa);for(var G=[],
z=0;z<x.M.length;z++){var K=x.M[z];if(K){var B=x.Pa[z],C=x.Va[z],L=x.Xa[z];if(0!=B.length||C||L){if(0<B.length)for(var T=xk(B,K.B),Q=0;Q<B.length;Q++)B[Q]instanceof Oj&&B[Q].w!=z&&wk(x,B[Q].w,T);(C||L)&&Bk(x,z)}else G.push(z)}}for(z=0;z<G.length;z++)x.M[G[z]].B();for(z=0;z<x.Ga.length;z++){for(var va=x.Ga[z],V=va,ka=[],ha=0;ha<V.length;ha++){var ob=V[ha],mb=ob.g,Lb=Ra[mb],md=Lb.firingOption;0!=md&&(1==md&&void 0!==ob.s.Ha[mb]||2==md&&void 0!==Lb.state)&&ka.push(ob)}var nd=Dk(ka),rc=void 0;for(rc in nd)if(nd.hasOwnProperty(rc)){for(var qf=
void 0,cj=void 0,jd=nd[rc],$k=jd[0],fj=jd[jd.length-1],gj,Ga=0;Ga<V.length;Ga++){var kd=V[Ga];!qf&&kd.g==$k&&0<Ga&&(qf=V[Ga-1]);kd.g==fj&&Ga<V.length-1&&(cj=V[Ga+1]);if(-1<bf(jd,kd.g))if(gj=V.splice(Ga,1)[0],kd.g==fj)break;else Ga--}if(gj){var hj=Number(rc),ma=qf,rf=cj;if(ma){var al=ma.pa[0],bl=ma.ka[0],ij=ma;ij.pa=[];ij.ka=[];sk(ma,al);tk(ma,bl)}if(ma&&rf){var sf=Ak(rf);sk(ma,sf);var tf=zk(ma.g,!1);0<tf.length&&tf[0].w!=hj&&0==tf[0].qa&&tk(ma,sf);var uf=zk(rf.g,!0);0<uf.length&&uf[0].w!=hj&&0==uf[0].qa&&
tk(ma,sf)}}}0<va.length&&va[0].B()}0<x.X||lf(x.ya);d&&M(d)&&d({passingRules:f,resolvedTags:e.T});
if("gtm.js"==b||"gtm.sync"==b)a:{}for(var lj in e.T)if(e.T.hasOwnProperty(lj)){var mj=e.T[lj],vf;if(!(vf=void 0==mj[Tc])){var nj=mj[Tc];vf=!("function"!=typeof String.prototype.startsWith?0===nj.indexOf("_implicit"):nj.startsWith("_implicit"))}if(vf)return!0}return!1};var Nk={macro:function(a){if(Hj.contains(a))return Hj.get(a)}};Nk.dataLayer=Of;Nk.onHtmlSuccess=Wg(!0);Nk.onHtmlFailure=Wg(!1);Nk.callback=function(a){Ea.hasOwnProperty(a)&&M(Ea[a])&&Ea[a]();delete Ea[a]};Nk.jb=function(){var a=v.google_tag_manager;a||(a=v.google_tag_manager={});a["GTM-PT2SNS"]||(a["GTM-PT2SNS"]=Nk);wa=a};(function(){var a=function(a){var b=O("google_tag_manager",{}),d=b[a];d||(d=b[a]={},d.nwnc={},d.nwc={},d.wnc={},d.wc={},d.wt=null,d.l=!1);return d};pi=a("linkClickMap");qi=a("formSubmitMap")})();
Ej.push.apply(Ej,function(){for(var a=[_eq,_e,'_event',_M(0),'gtm.js','1466085_2147479553',_asp,true,'VM7GKQD35BDCHP7J6NIB5M','M5G2HX3D4BDQ5GJR3OECRT',4,_sp,'956542766','',5,_html,'\x3cscript data-gtmsrc\x3d\x22//platform.twitter.com/oct.js\x22 type\x3d\x22text/gtmscript\x22\x3e\x3c/script\x3e\n\x3cscript type\x3d\x22text/gtmscript\x22\x3etwttr.conversion.trackPid(\x22ntplg\x22,{tw_sale_amount:0,tw_order_quantity:0});\x3c/script\x3e\n\x3cnoscript\x3e\n\x3cimg height\x3d\x221\x22 width\x3d\x221\x22 style\x3d\x22display:none;\x22 alt\x3d\x22\x22 src\x3d\x22https://analytics.twitter.com/i/adsct?txn_id\x3dntplg\x26amp;p_id\x3dTwitter\x26amp;tw_sale_amount\x3d0\x26amp;tw_order_quantity\x3d0\x22\x3e\n\x3cimg height\x3d\x221\x22 width\x3d\x221\x22 style\x3d\x22display:none;\x22 alt\x3d\x22\x22 src\x3d\x22//t.co/i/adsct?txn_id\x3dntplg\x26amp;p_id\x3dTwitter\x26amp;tw_sale_amount\x3d0\x26amp;tw_order_quantity\x3d0\x22\x3e\n\x3c/noscript\x3e',1,'\x3cscript type\x3d\x22text/gtmscript\x22\x3e!function(b,e,f,g,a,c,d){b.fbq||(a\x3db.fbq\x3dfunction(){a.callMethod?a.callMethod.apply(a,arguments):a.queue.push(arguments)},b._fbq||(b._fbq\x3da),a.push\x3da,a.loaded\x3d!0,a.version\x3d\x222.0\x22,a.queue\x3d[],c\x3de.createElement(f),c.async\x3d!0,c.src\x3dg,d\x3de.getElementsByTagName(f)[0],d.parentNode.insertBefore(c,d))}(window,document,\x22script\x22,\x22//connect.facebook.net/en_US/fbevents.js\x22);fbq(\x22init\x22,\x22417778941754366\x22);fbq(\x22track\x22,\x22PageView\x22);\x3c/script\x3e\n\x3cnoscript\x3e\x3cimg height\x3d\x221\x22 width\x3d\x221\x22 style\x3d\x22display:none\x22 src\x3d\x22https://www.facebook.com/tr?id\x3d417778941754366\x26amp;ev\x3dPageView\x26amp;noscript\x3d1\x22\x3e\x3c/noscript\x3e\n',3,_u,'Page URL','Page Hostname','host','Page Path','path',_f,'Referrer','Event'],b=[],c=0;c<a.length;c++)b[c]=Pj(c,a);return b}());Sj(Fj,0,"5:0,5:1,8:2,0:3,1:4,5:6,9:7,4:8,10:9,11:10,5:11,7:12,3:13,11:14,5:15,6:16,11:17,6:18,11:19,5:20,8:21,8:22,2:23,8:24,2:25,5:26,8:27,8:28");Sj(Gj,1,"G,AAAG,AAAa,AAAiB,AAAAG,CAAAI");Sj(Ij,1,"Z");Sj(Z,1,"gP,AxD,ABc,ABkB");Sj(Ei,2,"B:P::");Sj(Fi,4,"5.5.5.5:");for(var Ok=0;Ok<Z.length;Ok++){var Pk=Z[Ok],Qk=1;Pk[zd]?Qk=2:Pk[Ke]&&(Qk=0);Ra[Ok]={firingOption:Qk,state:void 0};Sa[Ok]=[]}Nk.jb();
(function(a){})("async");
(function(){var a=O("dataLayer",[]),b=O("google_tag_manager",{}),b=b["dataLayer"]=b["dataLayer"]||{};za.push(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});Hf.push(function(){b.gtmLoad||(b.gtmLoad=!0,a.push({event:"gtm.load"}))});var c=a.push;a.push=function(){var b=[].slice.call(arguments,0);c.apply(a,b);for(Tf.push.apply(Tf,b);300<this.length;)this.shift();return ag()};Tf.push.apply(Tf,a.slice(0));y(bg)})();var Yk=v;
if("interactive"==J.readyState&&!J.createEventObject||"complete"==J.readyState)Af();else{R(J,"DOMContentLoaded",Af);R(J,"readystatechange",Af);if(J.createEventObject&&J.documentElement.doScroll){var Zk=!0;try{Zk=!Yk.frameElement}catch(a){}Zk&&Cf()}R(Yk,"load",Af)}"complete"===J.readyState?If():R(v,"load",If);
(function(a){})("async");(function(){})();var _vs="res_ts:1446654140300000,srv_cl:136134251,ds:live,cv:3";
})()
