//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Admin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Admin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Admin", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have sufficient permission to add relations from product to other products on current product catalog.
        /// </summary>
        internal static string add_relations_from_product_to_other_products_message {
            get {
                return ResourceManager.GetString("add_relations_from_product_to_other_products_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps.
        /// </summary>
        internal static string Apps {
            get {
                return ResourceManager.GetString("Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete award?.
        /// </summary>
        internal static string AreYouSureDeleteAward_Text {
            get {
                return ResourceManager.GetString("AreYouSureDeleteAward.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change log.
        /// </summary>
        internal static string ChangeLog {
            get {
                return ResourceManager.GetString("ChangeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a File.
        /// </summary>
        internal static string ChooseAFile {
            get {
                return ResourceManager.GetString("ChooseAFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this item?.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Campaign.
        /// </summary>
        internal static string create_campaign {
            get {
                return ResourceManager.GetString("create_campaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Campaign Item.
        /// </summary>
        internal static string create_campaign_item {
            get {
                return ResourceManager.GetString("create_campaign_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Category.
        /// </summary>
        internal static string create_category {
            get {
                return ResourceManager.GetString("create_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Country.
        /// </summary>
        internal static string create_country {
            get {
                return ResourceManager.GetString("create_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Currency.
        /// </summary>
        internal static string create_currency {
            get {
                return ResourceManager.GetString("create_currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Data Type.
        /// </summary>
        internal static string create_datatype {
            get {
                return ResourceManager.GetString("create_datatype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Data Type Enum.
        /// </summary>
        internal static string create_datatypeenum {
            get {
                return ResourceManager.GetString("create_datatypeenum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Definition.
        /// </summary>
        internal static string create_definition {
            get {
                return ResourceManager.GetString("create_definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Definition Field.
        /// </summary>
        internal static string create_definitionfield {
            get {
                return ResourceManager.GetString("create_definitionfield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Email Profile.
        /// </summary>
        internal static string create_emailprofile {
            get {
                return ResourceManager.GetString("create_emailprofile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Email Type.
        /// </summary>
        internal static string create_emailtype {
            get {
                return ResourceManager.GetString("create_emailtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Order Numbers.
        /// </summary>
        internal static string create_ordernumber {
            get {
                return ResourceManager.GetString("create_ordernumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Payment Method.
        /// </summary>
        internal static string create_paymentmethod {
            get {
                return ResourceManager.GetString("create_paymentmethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Price Group.
        /// </summary>
        internal static string create_pricegroup {
            get {
                return ResourceManager.GetString("create_pricegroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Product.
        /// </summary>
        internal static string create_product {
            get {
                return ResourceManager.GetString("create_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Product Catalog.
        /// </summary>
        internal static string create_productcatalog {
            get {
                return ResourceManager.GetString("create_productcatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Product Catalog Group.
        /// </summary>
        internal static string create_productcataloggroup {
            get {
                return ResourceManager.GetString("create_productcataloggroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Product Definition.
        /// </summary>
        internal static string create_productdefinition {
            get {
                return ResourceManager.GetString("create_productdefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Product Definition Field.
        /// </summary>
        internal static string create_productdefinitionfield {
            get {
                return ResourceManager.GetString("create_productdefinitionfield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Product Relation Type.
        /// </summary>
        internal static string create_productRelationType {
            get {
                return ResourceManager.GetString("create_productRelationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Shipping Method.
        /// </summary>
        internal static string create_shippingmethod {
            get {
                return ResourceManager.GetString("create_shippingmethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer ID.
        /// </summary>
        internal static string CustomerIDParameter {
            get {
                return ResourceManager.GetString("CustomerIDParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected inheritance would cause a cyclic definition: &apos;{0}&apos;.
        /// </summary>
        internal static string cyclic_inheritance_error_message {
            get {
                return ResourceManager.GetString("cyclic_inheritance_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to definitions.
        /// </summary>
        internal static string Definitions {
            get {
                return ResourceManager.GetString("Definitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Campaign.
        /// </summary>
        internal static string delete_campaign {
            get {
                return ResourceManager.GetString("delete_campaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Campaign Item.
        /// </summary>
        internal static string delete_campaign_item {
            get {
                return ResourceManager.GetString("delete_campaign_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Category.
        /// </summary>
        internal static string delete_category {
            get {
                return ResourceManager.GetString("delete_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Country.
        /// </summary>
        internal static string delete_country {
            get {
                return ResourceManager.GetString("delete_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Currency.
        /// </summary>
        internal static string delete_currency {
            get {
                return ResourceManager.GetString("delete_currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Data Type.
        /// </summary>
        internal static string delete_datatype {
            get {
                return ResourceManager.GetString("delete_datatype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Data Type Enum.
        /// </summary>
        internal static string delete_datatypeenum {
            get {
                return ResourceManager.GetString("delete_datatypeenum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Definition.
        /// </summary>
        internal static string delete_definition {
            get {
                return ResourceManager.GetString("delete_definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Defintion Field.
        /// </summary>
        internal static string delete_definitionfield {
            get {
                return ResourceManager.GetString("delete_definitionfield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Email Profile.
        /// </summary>
        internal static string delete_emailprofile {
            get {
                return ResourceManager.GetString("delete_emailprofile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Email Type.
        /// </summary>
        internal static string delete_emailtype {
            get {
                return ResourceManager.GetString("delete_emailtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Order Number Series.
        /// </summary>
        internal static string delete_ordernumber {
            get {
                return ResourceManager.GetString("delete_ordernumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Payment Method.
        /// </summary>
        internal static string delete_paymentmethod {
            get {
                return ResourceManager.GetString("delete_paymentmethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Price Group.
        /// </summary>
        internal static string delete_pricegroup {
            get {
                return ResourceManager.GetString("delete_pricegroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Product.
        /// </summary>
        internal static string delete_product {
            get {
                return ResourceManager.GetString("delete_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Product Catalog.
        /// </summary>
        internal static string delete_productcatalog {
            get {
                return ResourceManager.GetString("delete_productcatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Product Catalog Group.
        /// </summary>
        internal static string delete_productcataloggroup {
            get {
                return ResourceManager.GetString("delete_productcataloggroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Product Definition.
        /// </summary>
        internal static string delete_productdefinition {
            get {
                return ResourceManager.GetString("delete_productdefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Product Definition Field.
        /// </summary>
        internal static string delete_productdefinitionField {
            get {
                return ResourceManager.GetString("delete_productdefinitionField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Product Relation Type.
        /// </summary>
        internal static string delete_productrelationtype {
            get {
                return ResourceManager.GetString("delete_productrelationtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have sufficient permission to delete products in current catalog..
        /// </summary>
        internal static string delete_product_error_message {
            get {
                return ResourceManager.GetString("delete_product_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Shipping Method.
        /// </summary>
        internal static string delete_shippingmethod {
            get {
                return ResourceManager.GetString("delete_shippingmethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        internal static string documentationText {
            get {
                return ResourceManager.GetString("documentationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected inheritance would cause a duplicate field : &apos;{0}&apos;..
        /// </summary>
        internal static string duplicate_name_inheritance_error_message {
            get {
                return ResourceManager.GetString("duplicate_name_inheritance_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name &apos;{0}&apos; is already present on this definition, or a child..
        /// </summary>
        internal static string duplicate_name_on_child_error_message {
            get {
                return ResourceManager.GetString("duplicate_name_on_child_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name &apos;{0}&apos; is already present on this definition, or a parent..
        /// </summary>
        internal static string duplicate_name_on_parent_error_message {
            get {
                return ResourceManager.GetString("duplicate_name_on_parent_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have sufficient permission to edit products in current catalog..
        /// </summary>
        internal static string edit_product_error_message {
            get {
                return ResourceManager.GetString("edit_product_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a value ....
        /// </summary>
        internal static string EnterValue {
            get {
                return ResourceManager.GetString("EnterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size is limited to {0} KB. Adjust limit in web.config/maxRequestLength to avoid this.
        /// </summary>
        internal static string FileIsToLarge {
            get {
                return ResourceManager.GetString("FileIsToLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has fields from.
        /// </summary>
        internal static string has_fields_from {
            get {
                return ResourceManager.GetString("has_fields_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string InstallAppButton {
            get {
                return ResourceManager.GetString("InstallAppButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install your App.
        /// </summary>
        internal static string InstallAppHeader {
            get {
                return ResourceManager.GetString("InstallAppHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string InstallApp_tab {
            get {
                return ResourceManager.GetString("InstallApp_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Apps.
        /// </summary>
        internal static string InstalledApps_tab {
            get {
                return ResourceManager.GetString("InstalledApps_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Apps.
        /// </summary>
        internal static string installed_apps {
            get {
                return ResourceManager.GetString("installed_apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install App.
        /// </summary>
        internal static string install_app {
            get {
                return ResourceManager.GetString("install_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO Code.
        /// </summary>
        internal static string isoCodeValidator_error {
            get {
                return ResourceManager.GetString("isoCodeValidator_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your license does not support any more..
        /// </summary>
        internal static string LicenseMessage {
            get {
                return ResourceManager.GetString("LicenseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reloading page.
        /// </summary>
        internal static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reloading page.
        /// </summary>
        internal static string LoadingText1 {
            get {
                return ResourceManager.GetString("LoadingText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string menu_analytics_orders_root {
            get {
                return ResourceManager.GetString("menu_analytics_orders_root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Sales.
        /// </summary>
        internal static string menu_analytics_orders_totalsales {
            get {
                return ResourceManager.GetString("menu_analytics_orders_totalsales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string menu_analytics_products_root {
            get {
                return ResourceManager.GetString("menu_analytics_products_root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytics.
        /// </summary>
        internal static string menu_analytics_root {
            get {
                return ResourceManager.GetString("menu_analytics_root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing.
        /// </summary>
        internal static string menu_marketing_root {
            get {
                return ResourceManager.GetString("menu_marketing_root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string menu_orders_root {
            get {
                return ResourceManager.GetString("menu_orders_root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string menu_order_search {
            get {
                return ResourceManager.GetString("menu_order_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stores.
        /// </summary>
        internal static string menu_productcatalog_root {
            get {
                return ResourceManager.GetString("menu_productcatalog_root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Groups.
        /// </summary>
        internal static string menu_settings_catalog_pricegroups {
            get {
                return ResourceManager.GetString("menu_settings_catalog_pricegroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Relations.
        /// </summary>
        internal static string menu_settings_catalog_productrelationtypes {
            get {
                return ResourceManager.GetString("menu_settings_catalog_productrelationtypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog.
        /// </summary>
        internal static string menu_settings_catalog_root {
            get {
                return ResourceManager.GetString("menu_settings_catalog_root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string menu_settings_create {
            get {
                return ResourceManager.GetString("menu_settings_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Types.
        /// </summary>
        internal static string menu_settings_definition_datatypes {
            get {
                return ResourceManager.GetString("menu_settings_definition_datatypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definitions.
        /// </summary>
        internal static string menu_settings_definition_definitions {
            get {
                return ResourceManager.GetString("menu_settings_definition_definitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Definitions.
        /// </summary>
        internal static string menu_settings_definition_definitions_categories {
            get {
                return ResourceManager.GetString("menu_settings_definition_definitions_categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Definitions.
        /// </summary>
        internal static string menu_settings_definition_definitions_products {
            get {
                return ResourceManager.GetString("menu_settings_definition_definitions_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definitions.
        /// </summary>
        internal static string menu_settings_definition_root {
            get {
                return ResourceManager.GetString("menu_settings_definition_root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string menu_settings_delete {
            get {
                return ResourceManager.GetString("menu_settings_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        internal static string menu_settings_email_profiles {
            get {
                return ResourceManager.GetString("menu_settings_email_profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string menu_settings_email_root {
            get {
                return ResourceManager.GetString("menu_settings_email_root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types.
        /// </summary>
        internal static string menu_settings_email_types {
            get {
                return ResourceManager.GetString("menu_settings_email_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string menu_settings_groupsecurity_root {
            get {
                return ResourceManager.GetString("menu_settings_groupsecurity_root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        internal static string menu_settings_orders_countries {
            get {
                return ResourceManager.GetString("menu_settings_orders_countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies.
        /// </summary>
        internal static string menu_settings_orders_currencies {
            get {
                return ResourceManager.GetString("menu_settings_orders_currencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Numbers.
        /// </summary>
        internal static string menu_settings_orders_ordernumbers {
            get {
                return ResourceManager.GetString("menu_settings_orders_ordernumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Methods.
        /// </summary>
        internal static string menu_settings_orders_paymentmethods {
            get {
                return ResourceManager.GetString("menu_settings_orders_paymentmethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string menu_settings_orders_root {
            get {
                return ResourceManager.GetString("menu_settings_orders_root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Methods.
        /// </summary>
        internal static string menu_settings_orders_shippingmethods {
            get {
                return ResourceManager.GetString("menu_settings_orders_shippingmethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string menu_settings_refresh {
            get {
                return ResourceManager.GetString("menu_settings_refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string menu_settings_root {
            get {
                return ResourceManager.GetString("menu_settings_root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string menu_settings_security_root {
            get {
                return ResourceManager.GetString("menu_settings_security_root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Methods.
        /// </summary>
        internal static string menu_settings_shippingmethods_root {
            get {
                return ResourceManager.GetString("menu_settings_shippingmethods_root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        internal static string menu_settings_sort {
            get {
                return ResourceManager.GetString("menu_settings_sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string menu_settings_usersecurity_root {
            get {
                return ResourceManager.GetString("menu_settings_usersecurity_root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more.
        /// </summary>
        internal static string more {
            get {
                return ResourceManager.GetString("more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string nameValidator_error {
            get {
                return ResourceManager.GetString("nameValidator_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No installed apps.
        /// </summary>
        internal static string NoInstalledApps {
            get {
                return ResourceManager.GetString("NoInstalledApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file type must be.
        /// </summary>
        internal static string NotSupportedFileType {
            get {
                return ResourceManager.GetString("NotSupportedFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name can contain only letters and numbers..
        /// </summary>
        internal static string numbersAndLettersOnlyInName {
            get {
                return ResourceManager.GetString("numbersAndLettersOnlyInName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID.
        /// </summary>
        internal static string OrderIDParameter {
            get {
                return ResourceManager.GetString("OrderIDParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prioritize Campaigns.
        /// </summary>
        internal static string prioritize_campaigns {
            get {
                return ResourceManager.GetString("prioritize_campaigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prioritize Campaign Items.
        /// </summary>
        internal static string prioritize_campaign_items {
            get {
                return ResourceManager.GetString("prioritize_campaign_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out our App store on apps.ucommerce.net..
        /// </summary>
        internal static string RedirectToAppsStore {
            get {
                return ResourceManager.GetString("RedirectToAppsStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Campaigns.
        /// </summary>
        internal static string refresh_campaigns {
            get {
                return ResourceManager.GetString("refresh_campaigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Campaign Items.
        /// </summary>
        internal static string refresh_campaign_items {
            get {
                return ResourceManager.GetString("refresh_campaign_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Catalog.
        /// </summary>
        internal static string refresh_catalog {
            get {
                return ResourceManager.GetString("refresh_catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Category.
        /// </summary>
        internal static string refresh_category {
            get {
                return ResourceManager.GetString("refresh_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Countries.
        /// </summary>
        internal static string refresh_countries {
            get {
                return ResourceManager.GetString("refresh_countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Currencies.
        /// </summary>
        internal static string refresh_currencies {
            get {
                return ResourceManager.GetString("refresh_currencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Data Type Enums.
        /// </summary>
        internal static string refresh_datatypeenums {
            get {
                return ResourceManager.GetString("refresh_datatypeenums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Data Types.
        /// </summary>
        internal static string refresh_datatypes {
            get {
                return ResourceManager.GetString("refresh_datatypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Definitions.
        /// </summary>
        internal static string refresh_definitions {
            get {
                return ResourceManager.GetString("refresh_definitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Email Profile.
        /// </summary>
        internal static string refresh_emailprofile {
            get {
                return ResourceManager.GetString("refresh_emailprofile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Email Profiles.
        /// </summary>
        internal static string refresh_emailprofiles {
            get {
                return ResourceManager.GetString("refresh_emailprofiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Email Types.
        /// </summary>
        internal static string refresh_emailtype {
            get {
                return ResourceManager.GetString("refresh_emailtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Catalog Settings.
        /// </summary>
        internal static string refresh_menu_settings_catalog_root {
            get {
                return ResourceManager.GetString("refresh_menu_settings_catalog_root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Definitions.
        /// </summary>
        internal static string refresh_menu_settings_definition_root {
            get {
                return ResourceManager.GetString("refresh_menu_settings_definition_root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Email Settings.
        /// </summary>
        internal static string refresh_menu_settings_email_root {
            get {
                return ResourceManager.GetString("refresh_menu_settings_email_root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Groups.
        /// </summary>
        internal static string refresh_menu_settings_groupsecurity_root {
            get {
                return ResourceManager.GetString("refresh_menu_settings_groupsecurity_root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Orders Settings.
        /// </summary>
        internal static string refresh_menu_settings_orders_root {
            get {
                return ResourceManager.GetString("refresh_menu_settings_orders_root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Settings.
        /// </summary>
        internal static string refresh_menu_settings_root {
            get {
                return ResourceManager.GetString("refresh_menu_settings_root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Security.
        /// </summary>
        internal static string refresh_menu_settings_security_root {
            get {
                return ResourceManager.GetString("refresh_menu_settings_security_root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Users.
        /// </summary>
        internal static string refresh_menu_settings_usersecurity_root {
            get {
                return ResourceManager.GetString("refresh_menu_settings_usersecurity_root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Order Numbers.
        /// </summary>
        internal static string refresh_ordernumber {
            get {
                return ResourceManager.GetString("refresh_ordernumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Orders.
        /// </summary>
        internal static string refresh_orders {
            get {
                return ResourceManager.GetString("refresh_orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Payment Methods.
        /// </summary>
        internal static string refresh_paymentmethods {
            get {
                return ResourceManager.GetString("refresh_paymentmethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Pricegroups.
        /// </summary>
        internal static string refresh_pricegroups {
            get {
                return ResourceManager.GetString("refresh_pricegroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Product.
        /// </summary>
        internal static string refresh_product {
            get {
                return ResourceManager.GetString("refresh_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Product Catalog Group.
        /// </summary>
        internal static string refresh_productcataloggroup {
            get {
                return ResourceManager.GetString("refresh_productcataloggroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Product Catalogs.
        /// </summary>
        internal static string refresh_productcatalogs {
            get {
                return ResourceManager.GetString("refresh_productcatalogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Product Definition Fields.
        /// </summary>
        internal static string refresh_productdefinitionfields {
            get {
                return ResourceManager.GetString("refresh_productdefinitionfields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Product Definitions.
        /// </summary>
        internal static string refresh_productdefinitions {
            get {
                return ResourceManager.GetString("refresh_productdefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Product Relation Types.
        /// </summary>
        internal static string refresh_productRelationTypes {
            get {
                return ResourceManager.GetString("refresh_productRelationTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Shipping Methods.
        /// </summary>
        internal static string refresh_shippingmethods {
            get {
                return ResourceManager.GetString("refresh_shippingmethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string remove_content {
            get {
                return ResourceManager.GetString("remove_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Orders.
        /// </summary>
        internal static string search_orders {
            get {
                return ResourceManager.GetString("search_orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose....
        /// </summary>
        internal static string select_content {
            get {
                return ResourceManager.GetString("select_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Content.
        /// </summary>
        internal static string select_content_header {
            get {
                return ResourceManager.GetString("select_content_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select content from the tree below..
        /// </summary>
        internal static string select_content_tiny_header {
            get {
                return ResourceManager.GetString("select_content_tiny_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select image.
        /// </summary>
        internal static string select_image_header {
            get {
                return ResourceManager.GetString("select_image_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an image from the tree below..
        /// </summary>
        internal static string select_image_tiny_header {
            get {
                return ResourceManager.GetString("select_image_tiny_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string select_item {
            get {
                return ResourceManager.GetString("select_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        internal static string select_or {
            get {
                return ResourceManager.GetString("select_or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps.
        /// </summary>
        internal static string settings_apps {
            get {
                return ResourceManager.GetString("settings_apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Catalogs.
        /// </summary>
        internal static string sort_catalogs {
            get {
                return ResourceManager.GetString("sort_catalogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Categories.
        /// </summary>
        internal static string sort_categories {
            get {
                return ResourceManager.GetString("sort_categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Definitions.
        /// </summary>
        internal static string sort_definitions {
            get {
                return ResourceManager.GetString("sort_definitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Parent Definitions.
        /// </summary>
        internal static string sort_definition_relations {
            get {
                return ResourceManager.GetString("sort_definition_relations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Product Definition Fields.
        /// </summary>
        internal static string sort_productdefinitionfields {
            get {
                return ResourceManager.GetString("sort_productdefinitionfields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string supportText {
            get {
                return ResourceManager.GetString("supportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        internal static string UninstallButton {
            get {
                return ResourceManager.GetString("UninstallButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string UploadAppButton {
            get {
                return ResourceManager.GetString("UploadAppButton", resourceCulture);
            }
        }
    }
}
