//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RoleName {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RoleName() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RoleName", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytics.
        /// </summary>
        internal static string AnalyticsRole {
            get {
                return ResourceManager.GetString("AnalyticsRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create store.
        /// </summary>
        internal static string CreateProductCatalogGroupRole {
            get {
                return ResourceManager.GetString("CreateProductCatalogGroupRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create product catalog.
        /// </summary>
        internal static string CreateProductCatalogRole {
            get {
                return ResourceManager.GetString("CreateProductCatalogRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create product.
        /// </summary>
        internal static string CreateProductRole {
            get {
                return ResourceManager.GetString("CreateProductRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete store.
        /// </summary>
        internal static string DeleteProductCatalogGroupRole {
            get {
                return ResourceManager.GetString("DeleteProductCatalogGroupRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete product catalog.
        /// </summary>
        internal static string DeleteProductCatalogRole {
            get {
                return ResourceManager.GetString("DeleteProductCatalogRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete product.
        /// </summary>
        internal static string DeleteProductRole {
            get {
                return ResourceManager.GetString("DeleteProductRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change order status.
        /// </summary>
        internal static string EditOrderStatusRole {
            get {
                return ResourceManager.GetString("EditOrderStatusRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit order.
        /// </summary>
        internal static string EditPurchaseOrderRole {
            get {
                return ResourceManager.GetString("EditPurchaseOrderRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string LanguageRoleRoot {
            get {
                return ResourceManager.GetString("LanguageRoleRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing.
        /// </summary>
        internal static string MarketingRole {
            get {
                return ResourceManager.GetString("MarketingRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price groups.
        /// </summary>
        internal static string PriceGroupRoleRoot {
            get {
                return ResourceManager.GetString("PriceGroupRoleRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Orders.
        /// </summary>
        internal static string PurchaseOrderRole {
            get {
                return ResourceManager.GetString("PurchaseOrderRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsRole {
            get {
                return ResourceManager.GetString("SettingsRole", resourceCulture);
            }
        }
    }
}
